# UniPi Student Notes
# CI Template - you shouldn't have a reason to edit this

sudo: required
language: generic
services: docker

script:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c 'cd src; tectonic "Reti di Calcolatori.tex"'

after_success:
  - mv "src/Reti di Calcolatori.pdf" reti-di-calcolatori.pdf
  - body="**Ultima revisione**\n"
  - body+="[Download - Reti di Calcolatori](https://github.com/$TRAVIS_REPO_SLUG/releases/download/continuous/reti-di-calcolatori.pdf)";
    export UPLOADTOOL_BODY=$body
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh reti-di-calcolatori.pdf

branches:
  except:
    - /^(?i:continuous)$/
